# Generated by Django 5.2.14 on 2026-05-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('plateforme', models.CharField(choices=[('google', 'Google'), ('trustpilot', 'Trustpilot'), ('tripadvisor', 'TripAdvisor'), ('autre', 'Autre')], max_length=50)),
                ('auteur_avis', models.CharField(max_length=200)),
                ('note', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')])),
                ('contenu_avis', models.TextField()),
                ('reponse_generee', models.TextField()),
                ('reponse_finale', models.TextField(blank=True)),
                ('publiee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
